\documentclass[11pt]{article}
\usepackage{graphicx, verbatim}
\usepackage{caption}
\usepackage{hyperref}
\usepackage{url}
\setlength{\textwidth}{6.5in} 
\setlength{\textheight}{9in}
\setlength{\oddsidemargin}{0in} 
\setlength{\evensidemargin}{0in}
\setlength{\topmargin}{-1.5cm}

<<load_lib,include=FALSE,results="hide">>=
library(data.table)
library(doMC)
library(fields)
library(ggplot2)
library(plyr)
library(R.utils)
library(scales)
source("get_file_paths.R")
@

<<set_file_path,echo=FALSE>>=
this_analysis_path = file.path(PROJ_RESULTS_PATH,"analyze_star_junctions_2014-12-14")
prefix.string = file.path(this_analysis_path,"graphics","analyze_star_junctions_2014-12-14-")
rdata_prefix = file.path(this_analysis_path,"analyze_star_junctions_2014-12-14-")
step_list = "load_junctions_dt"
@

\begin{document}
<<setup, include=FALSE, cache=FALSE>>=
# set global chunk options
opts_chunk$set(cache = TRUE) # enable cache to make it faster
opts_chunk$set(fig.path=prefix.string, fig.align='center', fig.show='hold',
               eval=TRUE,echo=TRUE,include=TRUE)

knit_hooks$set(checkpoint = function(before, options, envir) {
  # e.g. we skip all chunks after the chunk example-b
  if (!before && options$label == options$checkpoint) {
    opts_chunk$set(cache = FALSE, eval = FALSE, echo = FALSE, include = FALSE)
    # you can do other things like dumping `envir` into globalenv(), e.g.
    # assign('ChunkEnv', envir, envir = globalenv())
  }
})
## set checkpoint=NULL to disable checkpoints
opts_chunk$set(checkpoint = 'sessionInfo') # restore objects up to exmple-b
## now if you knit() this document, only x exists; y is not loaded
@

\title{1001 transcriptome STAR aligner junctions}
\date{December 14, 2014}

\maketitle

\section{Settings}

\begin{itemize}
\item This analysis was run on \Sexpr{System$getHostname()}.
\item rmake data in \\ \verb|\Sexpr{tfq_oberon_path}|.
\end{itemize}

<<setup_parallel>>=
registerDoMC(11)
getDoParWorkers()
@

<<make_junctions_dt,echo=FALSE,results="hide",cache=TRUE>>=
junctions_dt = rbindlist(alply(fq_match_salk,1,function(acc) {
    junctions_bed = file.path(tfq_oberon_path,acc[1,'tg_ecotypeid'],
        paste0(acc[1,'tg_ecotypeid'],".bam.junctions.merged.bed"))
    if (file.exists(junctions_bed) & file.info(junctions_bed)$size>0) {
        dt = fread(junctions_bed)
        return(cbind(tg_ecotypeid=acc[1,'tg_ecotypeid'],dt))
    }
},.parallel=T))
  
setnames(junctions_dt,c("tg_ecotypeid","chr","start","end",                        
                        "strand","motif","annot","UM","MM",
                        "max_overhang"))
#junctions_dt[,intron_id:=paste0(chr,":",start,"-",end,"_",strand)]
junctions_acc = junctions_dt[,list(UM=sum(UM),MM=sum(MM),
    annot=annot[1],motif=motif[1]),
    by=c("tg_ecotypeid","chr","start","end","strand")]
  
save(junctions_dt,file=paste0(rdata_prefix,'junctions_dt.RData'))
save(junctions_acc,file=paste0(rdata_prefix,'junctions_acc.RData'))
rm(junctions_dt,junctions_acc)
@

<<load_junctions_dt,cache=FALSE>>=
load(paste0(rdata_prefix,'junctions_dt.RData'))
load(paste0(rdata_prefix,'junctions_acc.RData'))
@

<<bam_mapped_df>>=
bam_mapped_df = read.table(file.path(PROJ_RESULTS_PATH,"tbam_stats_2014-11-18","graphics","tbam_stats_2014-11-18-tbam_mapped.txt"),sep='\t',header=T,stringsAsFactors=F)
bam_mapped_df = merge(bam_mapped_df,merge_list_1001g,by.x="sample_id1",
                      by.y="tg_ecotypeid")

bam_mapped_df = within(bam_mapped_df,{
    tg_ecotypeid = as.integer(sample_id1)
    tg_ecotypeid_x = paste0("X",sample_id1)
})
@

<<star_junc_code>>=
annot_names = c("0"="unannotated","1"="annotated")
motif_names = c("0"="NC","1"="GT/AG",
                   "2"="CT/AC","3"="GC/AG","4"="CT/GC",
                   "5"="AT/AC","6"="GT/AT")
@ 

<<intron_by_acc>>=
intron_by_acc = junctions_acc[,list(n_acc=.N,UM_med=median(as.numeric(UM)),
    UM_min=min(as.numeric(UM)),
    annot=annot[1],motif=motif[1]),
    by=c("chr","start","end","strand")]
@

<<intron_type_distr,fig.width=4,fig.height=3>>=
p4a = ggplot(intron_by_acc[UM_med>=2 & n_acc>=2,],aes(x=factor(annot)))
p4b = p4a + geom_bar(aes(fill=factor(motif)),width=0.5)
p4c = p4b + scale_x_discrete("",breaks=c(0,1),labels=c("unannotated","annotated")) +
    scale_fill_discrete("Motif",breaks=0:6,labels=motif_names) +
    ylab("Number of junctions") +
    theme_bw()
print(p4c)
@ 

<<intron_by_acc_plot,fig.width=6,fig.height=3>>=
junc_labeller <- function(var, value){
    value <- as.character(value)
    if (var=="annot") {
        return(annot_names[value])
    } else if (var=="motif") {
       return(motif_names[value])
    }    
}

njuncs_dt = intron_by_acc[UM_med>=2 & n_acc>=2,.N,by=c("annot")]

p1a = ggplot(data=intron_by_acc[UM_med>=2 & n_acc>=2,],aes(x=UM_med,y=n_acc))
p1b = p1a + stat_bin2d(bins=50) +
  facet_grid(~annot,labeller=junc_labeller) +
  geom_text(data=njuncs_dt,aes(x=10000,y=50,label=paste("n =",N),
                               hjust=0.6,vjust=0.5))
p1c = p1b + 
  scale_x_log10("Median uniquely mapped reads across junction",
                     breaks = trans_breaks("log10", function(x) 10^x)) +
  ylab("Number of accessions") +
  scale_fill_gradientn("Number of\njunctions",colours=tim.colors(50)) +
  theme_bw() +
  theme(axis.text.x=element_text(angle=30,hjust=1))
print(p1c)
@ 

<<intron_per_acc>>=
intron_per_acc = junctions_acc[,list(n_junc=.N,UM_med=median(as.numeric(UM))),
                               by=c("tg_ecotypeid","motif","annot")]
intron_per_acc[,motif_annot:=paste0(motif,"_",annot)]

intron_per_acc = merge(intron_per_acc,bam_mapped_df[,c('tg_ecotypeid','MAPPED')],
    by=c("tg_ecotypeid"))
@

<<acc_intron_hist,fig.width=6.5,fig.height=3>>=
p2a = ggplot(data=intron_per_acc[UM_med>=2,],aes(x=n_junc))
p2b = p2a + geom_histogram(fill="grey20") + 
  facet_grid(annot~motif,scales="free",labeller=junc_labeller)
p2c = p2b + 
  xlab("Number of junctions found in an accession") +
  ylab("Number of accessions") +
  theme_bw() + 
  theme(axis.text.x=element_text(angle=90,hjust=1))
print(p2c)
@

<<intron_acc_hist_annot1,fig.width=2.5,fig.height=6>>=
p3a = ggplot(data=intron_by_acc[UM_med>=2 & annot==1 & n_acc>=2,],aes(x=n_acc))
p3b = p3a + geom_histogram(fill="grey20") + 
  facet_grid(motif~annot,scales="free",labeller=junc_labeller)
p3c = p3b + 
  xlab("Number of accessions\nwith the junction") +
  ylab("Number of junctions") +
  theme_bw() + 
  theme(axis.text.x=element_text(angle=45,hjust=1))
print(p3c)
@
<<intron_acc_hist_annot0,fig.width=2.5,fig.height=6>>=
p3c %+% intron_by_acc[UM_med>=2 & annot==0 & n_acc>=2,]
@

<<intron_vs_mapped,fig.width=3.5,fig.height=6>>=
p5a = ggplot(data=intron_per_acc[UM_med>=2,],aes(x=MAPPED,y=n_junc))
p5b = p5a + geom_point() +
    facet_grid(motif~annot,scales="free_y",labeller=junc_labeller)
p5c = p5b + scale_x_log10("Number of mapped reads",
                     breaks = trans_breaks("log10", function(x) 10^x)) +
     ylab("Number of junctions") +
    theme_bw() +
    theme(axis.text.x=element_text(angle=30,hjust=1))
print(p5c)
@ 

<<sessionInfo>>=
sessionInfo()
@

\end{document}
